services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ideagallery'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  thumbor:
    image: ghcr.io/minimalcompact/thumbor
    ports:
      - '8888:80'
    restart: always
    volumes:
      - './thumbor.conf:/app/thumbor.conf'
      - './result_storage:/tmp/thumbor/result_storage'
      - './storage:/tmp/thumbor/storage'
    environment:
      - STORAGE=thumbor.storages.file_storage
      - FILE_STORAGE_ROOT_PATH=/tmp/thumbor/storage
      - RESULT_STORAGE=thumbor.result_storages.file_storage
      - STORAGE_EXPIRATION_SECONDS=86400
      - CORS_ALLOW_ORIGIN=*
